# Generated by Django 4.0.6 on 2023-03-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobNo', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('msg_dec', models.CharField(max_length=200)),
            ],
        ),
    ]
